---
title: "CV & Replicação"
output:
  blogdown::html_page:
    toc: true
---


## CV (Versão para Impressão)

[Clique aqui](https://github.com/rocha-felipeferreira/personal_site/blob/master/public/CV_PT.pdf){target="_blank"} para acessar a versão em PDF de meu CV. 

## Educação

- **Março de 2017 — Presente**

    - Doutorando em Ciência Política, Universidade Federal de Pernambuco — UFPE (Recife, Brasil) com período de estágio {doutorado sanduíche} no [Latin American Centre - University of Oxford](https://www.lac.ox.ac.uk/people/felipe-rocha-0){target="_blank"}

    - Comparando Agendas Diplomáticas: Ênfases Temáticas de Presidentes e Chanceleres Brasileiros (1995 - 2019) [Título Provisório da Tese]

- **Março de 2015 — Fevereiro de 2017**

    - Mestrado em Ciência Política, Universidade Federal de Pernambuco — UFPE (Recife, Brasil)

    - [O Uso dos Conceitos de América Latina e de América do Sul pela Diplomacia Brasileira de 1995 a 2014](https://repositorio.ufpe.br/handle/123456789/23655){target="_blank"}
 
- **Fevereiro de 2011 — Dezembro de 2014**

     - Graduação em Relações Internacionais, Universidade Federal de Sergipe — UFS (São Cristóvão - Brasil)

## Produções 

### Artigos publicados em Periódicos

<details closed>
<summary>2018</summary>
<br>
[ROCHA, Felipe Ferreira de Oliveira; ALBUQUERQUE, Rodrigo ; MEDEIROS, M. A. . Do Concepts Matter? Latin America and South America in the Discourse of Brazilian Foreign Policymakers. BRAZILIAN POLITICAL SCIENCE REVIEW, v. 12, p. 1-24, 2018.](https://doi.org/10.1590/1981-3821201800030006){target="_blank"}

  - [Arquivos para replicação](https://doi.org/10.7910/DVN/LYNZVO){target="_blank"}

[ROCHA, Felipe Ferreira de Oliveira. O exercício da liderança regional: um balanço preliminar a partir das opiniões de brasileiros e mexicanos. Conjuntura Austral. Revista do Núcleo Brasileiro de Estratégia e Relações Internacionais da UFRGS, v. 9, p. 20-36, 2018.](https://doi.org/10.22456/2178-8839.83922){target="_blank"}

   - [Arquivos para replicação](https://github.com/rocha-felipeferreira/paper-lider-reg-brasil-mex){target="_blank"}
</details>

<details closed>
<summary>2017</summary>
<br>
[ROCHA, F. F. O.. A academia perante a diplomacia no Brasil: o uso dos conceitos de América Latina e de América do Sul de 1985 a 2015. CONJUNTURA INTERNACIONAL (BELO HORIZONTE. ONLINE), v. 13, p. 126-139, 2017.](https://doi.org/10.5752/P.1809-6182.2016v13n3p126){target="_blank"}

 - [Arquivos para replicação](https://doi.org/10.7910/DVN/ZVPJSP){target="_blank"}
 
[ROCHA, Felipe Ferreira de Oliveira. Temas de Relações Internacionais nos discursos de posse de presidentes e de chanceleres brasileiros (1995-2017). Carta Internacional, v. 12, p. 153-174, 2017.](https://doi.org/10.21530/ci.v12n3.2017.707){target="_blank"}

  - [Arquivos para replicação](https://doi.org/10.7910/DVN/MQCASI){target="_blank"}
</details>


<details closed>
<summary>2016</summary>
<br>
BARNABÉ, I. R. ; ROCHA, F. F. O. . O Projeto Café Debate e a Internacionalização do Estado de Sergipe. Revista Interdisciplinar de Pesquisa e Inovação, v. 2, p. 1-8, 2016.
</details>

### Resenhas de Livros: 

<details closed>
<summary>2019</summary>
<br>
[ROCHA, F. F. O.. Política Externa e Participação Social: Trajetórias e perspectivas. Belo Horizonte: Conjuntura Internacional, Vol. 16 (2), 2019 (Resenha).](http://periodicos.pucminas.br/index.php/conjuntura/article/view/20377/16390){target="_blank"}
</details>

<br>
<details closed>
<summary>2018</summary>
<br>
[ROCHA, F. F. O.. Resenha 'Aspirational Power: Brazil on the Long Road to Global Influence'. João Pessoa: Revista de Estudos Internacionais (REI), Vol.9 (2), 2018 (Resenha).](http://www.revistadeestudosinternacionais.com/uepb/index.php/rei/article/view/389/pdf){target="_blank"}
</details>


### Apresentações em Eventos Científicos:

<details closed>
<summary>2019</summary>
<br>
[ROCHA, Felipe Ferreira de Oliveira; MEDEIROS, M. A. . A Análise de Política Externa sob o Prisma Bibliométrico (1969-2019). In: 7º Encontro da ABRI, 2019, Belo Horizonte. Anais do 7º Encontro da Associação Brasileira de Relações Internacionais - Atores e Agendas: interconexões, desafios e oportunidades, 2019.](https://www.encontro2019.abri.org.br/site/anais2?AREA=6){target="_blank"}

[ROCHA, Felipe Ferreira de Oliveira. Mensurando Ênfases Temáticas de Presidentes e de Chanceleres Brasileiros (1995 - 2014). In: 7º Encontro da ABRI, 2019, Belo Horizonte. Anais do 7º Encontro da Associação Brasileira de Relações Internacionais - Atores e Agendas: interconexões, desafios e oportunidades, 2019.](https://www.encontro2019.abri.org.br/site/anais2?AREA=13){target="_blank"}

</details>


<details closed>
<summary>2018</summary>
<br>
[ROCHA, Felipe Ferreira de Oliveira. O Regionalismo Americano nos Discursos de FHC e de Lula. In: 42º Encontro Anual da Anpocs, 2018, Caxambú. 42º Encontro Anual da Anpocs - GT27: Relações Internacionais da América Latina. Caxambú, 2018. v. 42.](https://www.anpocs.com/index.php/encontros/papers/42-encontro-anual-da-anpocs/gt-31/gt27-16/11346-o-regionalismo-americano-nos-discursos-de-fhc-e-de-lula/file){target="_blank"} </li>

  - [Arquivos para replicação](https://github.com/rocha-felipeferreira/conference_american_reg_fhc_lula){target="_blank"}
</details>



<details closed>
<summary>2017</summary>
<br>
ROCHA, Felipe Ferreira de Oliveira. Analisar a Política Externa Brasileira através do Conceito de Saliência Temática: Por que e Como?. In: IV Congresso Internacional de Pernambuco, 2017, Recife. O lugar dos BRICS nas relações internacionais contemporâneas: dilemas, posicionamentos e perspectivas: Anais do IV Congresso Internacional de Pernambuco.. Recife. p. 69-79.
</details>


<details closed>
<summary>2016</summary>
<br>
[BARROS, A. T. D. L. ; ROCHA, F. F. O. ; SANTOS, K. A. ; SILVA, L. P. ; NASCIMENTO, L. N. . A Liberdade Econômica Explica a Democracia Latino-Americana?. In: 40º Encontro Anual da ANPOCS, 2016, Caxambu. ST09 Democracia e desigualdades, 2016. p. 1-26.](https://www.anpocs.com/index.php/papers-40-encontro/st-10/st09-9/10222-a-liberdade-economica-explica-a-democracia-latinoamericana/file){target="_blank"}
</details>

