---
title: "Projetos"
output:
  blogdown::html_page
    
---

## 1. Comparando Agendas Retóricas dos Tomadores de Decisão da PEB

O objetivo primário desse projeto é realizar análises empíricas de longa duração para descobrir e comparar a agenda retórica dos principais atores envolvidos com a Política Externa Brasileira (PEB). Nesse sentido, minha tese de doutorado e minha dissertação de mestrado são ambas partes desse empreendimento. Na dissertação, eu avaliei a construção histórica por trás da narrativa e do uso dos conceitos de América Latina e América do Sul na diplomacia brasileira de 1995 a 2014. Agora, na minha pesquisa de tese, estou comparando as ênfases temáticas dos Presidentes e Chanceleres brasileiros com o intuito de descobrir se eles priorizam temas equivalentes ou não. 

## 2. Política Externa Brasileira: Abordagens e Metodologias 
 
Base metodológica do primeiro projeto, essa iniciativa objetiva explorar, avaliar, selecionar e empregar todas as abordagens e métodos plausíveis para melhor estudar a complexa realidade que cerca o processo de tomada de decisão da PEB. 
