---
title: "Projects"
output:
  blogdown::html_page
    
---

## 1. Comparing Rhetorical Agendas of Brazilian Foreign Policymakers

The primary objective of this project is to carry out a long-term empirical analysis to discover and to compare the rhetorical agenda of the main actors involved with the Brazilian Foreign Policy. In this regard, my doctoral thesis and my master’s dissertation are both part and parcel of this undertaking. In the latter, I evaluated the historical construction behind the narrative and the use of the concepts of Latin America and South America in Brazilian diplomacy from 1995 to 2014. Now, in my thesis research, I am comparing thematic emphases of Brazilian Presidents and Chancellors to discover whether they managed to prioritize equivalent themes.  



## 2. Brazilian Foreign Policy: Approaches and Methodologies
 
Methodological basis of the first project, I set out this initiative with the aim of exploring, assessing, selecting, and employing all plausible approaches and methods to better study the complex reality encompassing the Brazilian Foreign Policy decision making. 